import Head from "next/head";
import { DefaultHeader } from "../headers";

/**
 * @typedef {{
 *    backgroundColor: import("csstype").Property.BackgroundColor,
 *    children: React.ReactNode,
 *    "paint-header-on-scroll"?: boolean,
 *    title?: string
 * }} MainWrapperProps
 */

/**
 * Main Layout wrapper for pages, with the default header and footer.
 * @type {React.FC<MainWrapperProps>}
 */
export const MainWrapper = (props) => {
  return (
    <>
      <Head>
        <title>{props.title ?? "Jade Media Pro"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
        <link rel="icon" href="/favicon.ico" />
        <style>{`body {background-color: ${props.backgroundColor}}`}</style>
      </Head>
      <DefaultHeader
        backgroundColor={props.backgroundColor}
        paintOnScroll={props["paint-header-on-scroll"]}
      />
      {props.children}
      {/* <Footer/> */}
    </>
  );
};
